### ISSUE TITLE
NoSuchMethodError when running with Java 8.

### ISSUE THREAD

**Issue by jfarwer** [benfortuna/mstor#29]
Hi,
I get 

`java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer; 
at net.fortuna.mstor.data.MboxFile.read(MboxFile.java:267)`

when running with Java 8. It works fine with Java 11. It seems like this issue comes up when compiling code with one version of Java and then running it with a different version (https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip). So it sounds like two versions of Mstor are needed: One compiled with java 8 and one compiled with Java 11. Would it be possible to have a version of Mstor compiled with Java 8? 

Many thanks

**Comment by benfortuna** [comment]
I've added a `release = 8` flag to build options, which hopefully will resolve compatibility with java 8:

https://docs.gradle.org/current/userguide/building_java_projects.html#sec:java_cross_compilation

**Comment by jfarwer** [comment]
Thanks, that works.
